#!/bin/bash
clear

NOWF=$(date +"%d-%m-%Y %T")
echo Time $NOWF
echo "Текущий каталог " $PWD
echo Time $NOWF>>log.txt


export GOPATH=$PWD
export GOROOT=$HOME/go
export PATH=$PATH:$GOROOT/bin

#echo Start GO programm
go build -o essproxy
./essproxy
