#!/bin/bash

clear
echo Start
echo

export GOPATH=$PWD
export GOROOT=$HOME/go
export PATH=$PATH:$GOROOT/bin

go build -o mon
./mon "Prizm" "Module" "Send to log server" "info" "0x37cc62924b876a043bad996399d3bc15f0f629f01e1ef6c457b1b486681a568c" "Acc092"


